FYP/FYP/urls.py
from django.urls import include, path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('onlinequiz/', include('onlinequiz.urls')),
    path('admin/', admin.site.urls),
    path('markdownx/', include('markdownx.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FYP/onlinequiz/urls.py
from django.urls import include, path, re_path
from django.views.generic.base import TemplateView
from . import views
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', auth_views.login, name='login'),
    path('check_user/', views.checkUser, name="check_user"),
    path('logout/', auth_views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('account/', views.accountRedirect, name='accountRedirect'),
    path('account/acc-details/edit/', views.accountEdit, name='accountEdit'),
    path('account/<slug:current_menu>', views.account, name='account'),
    path('account/submissions/<int:id>', views.submissionDetails, name='submissionDetails'),
    path('account/test/<int:id>', views.testDetails, name='testDetails'),
    path('unlock_hint/', views.unlockHint, name='unlockHint'),
    path('test-cases/<int:id>', views.getTestCase, name='getTestCase'),
    path('ajax/load-questions', views.loadQuestion, name='loadQuestion'),
    # submit code
    re_path(r'^(?P<mode>[Practice|Challenge|Test]+)/(?P<set_id>\d+)/(?P<question_id>\d+)/submit_code/$', views.submitCodeAjax, name='submitCode'),
    # submit mcq
    re_path(r'^(?P<mode>[Practice|Challenge|Test]+)/(?P<set_id>\d+)/(?P<question_id>\d+)/submit_mcq/$', views.submitMcqAjax, name='submitMcq'),
    # display modes (practice/game/test)
    re_path(r'^(?P<mode>[Practice|Challenge|Test]+)/$', views.modeIndex, name='modeIndex'),
    # display modes' questions (practice/game/test)
    re_path(r'^(?P<mode>[Practice|Challenge|Test]+)/(?P<set_id>\d+)/$', views.modeIndexQn, name='modeIndexQn'),
    # display modes' questions (practice/game/test)
    re_path(r'^Test/(?P<set_id>\d+)/start/$', views.startTest, name='startTest'),
    # display questions
    re_path(r'^(?P<mode>[Practice|Challenge|Test]+)/(?P<set_id>\d+)/(?P<question_id>\d+)/$', views.detail, name='questionDetail'),
    #ex: /onlinequiz/5
    re_path(r'^(?P<question_id>\d+)/$', views.detail, name='detail'),
    re_path(r'^editor/$', TemplateView.as_view(
        template_name="editor.html"
    ), name='editor'),
]# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FYP/onlinequiz/forms.py
from django import forms
from .models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import BaseInlineFormSet

class CodeForm(forms.Form):
    # matric = forms.CharField(label='Matric No', max_length=100)
    submission = forms.CharField(label='Submission', widget=forms.Textarea)
    points = forms.IntegerField(widget=forms.HiddenInput)
    submission_type = forms.IntegerField(widget=forms.HiddenInput)

class MCQForm(forms.Form):
    def __init__(self, *args, **kwargs):
        choice_list = kwargs.pop('choice_list', None)
        super(MCQForm, self).__init__(*args, **kwargs)
        self.fields['choice'] = forms.ModelChoiceField(queryset=choice_list, widget=forms.RadioSelect, empty_label=None)

    # choice = forms.ModelChoiceField(queryset=Choice.objects.all(), widget=forms.RadioSelect)

class SignUpForm(UserCreationForm):
    matric = forms.CharField(max_length=15, required=True)
    group = forms.CharField(max_length=20, required=False)
    char_gender = forms.ChoiceField(choices=StudentUser.GENDER_CHOICES, widget=forms.RadioSelect, required=True)
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2', )

class UserForm(forms.ModelForm):
    password = forms.CharField(required=False, widget=forms.PasswordInput, help_text="Leave blank if you do not wish to change")
    confirm_password = forms.CharField(required=False, widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ('password', )

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")
        if password != confirm_password:
            raise forms.ValidationError(
                "Password is not the same"
            )
        if not(self.instance.has_usable_password()) and not(password):
            raise forms.ValidationError(
                "Please set a password for your account"
            )



class HiddenDeleteBaseInlineFormSet(BaseInlineFormSet):
    """
    Makes the delete field a hidden input rather than the default checkbox

    inlineformset_factory(Book, Page, formset=HiddenDeleteBaseInlineFormSet, can_delete=True)
    """

    def add_fields(self, form, index):
        super(HiddenDeleteBaseInlineFormSet, self).add_fields(form, index)
        if self.can_delete:
            form.fields[DELETION_FIELD_NAME] = forms.BooleanField(
                label=_('Delete'),
                required=False,
                widget=forms.HiddenInput
            )

FYP/onlinequiz/views/account_view.py
from django.shortcuts import get_object_or_404, render, redirect
from django.core import serializers
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.http import JsonResponse
from django.template import loader
from django.db.models.aggregates import Max
from django.db.models import IntegerField
from onlinequiz.forms import *
from django.forms.models import inlineformset_factory
import html
from onlinequiz.models import *
from markdownx.utils import markdownify

menu_list = {
    'acc-details': {
        'name': 'Account Details',
        'html': 'onlinequiz/account_details.html'
    },
    'submissions': {
        'name': 'Submissions',
        'html': 'onlinequiz/account_submissions.html'
    },
    'challenge': {
        'name': 'Challenge Statistics',
        'html': 'onlinequiz/account_challenge.html'
    },
    'test': {
        'name': 'Test Results',
        'html': 'onlinequiz/account_test.html'
    },
}

def accountEdit(request):
    """
    Allows student to edit their particulars

    :param request: submitted request
    :type request: HttpRequest
    :return: Renders account_edit page
    """
    context = {
        'menu_list': {k: v['name'] for k, v in menu_list.items()},
        'current_menu': 'acc-details'
    }
    user = request.user
    user_form = UserForm(instance=user)
    ProfileInlineFormset = inlineformset_factory(User, StudentUser, fields=('matric', 'group', 'char_gender'), can_delete=False)
    formset = ProfileInlineFormset(instance=user)

    if request.method == "POST":
        user_form = UserForm(request.POST, instance=user)
        formset = ProfileInlineFormset(request.POST, instance=user)

        if user_form.is_valid():
            password = user_form.cleaned_data['password']
            if (password):
                created_user = user_form.save(commit=False)
                created_user.set_password(password)
                created_user.save()
            formset.save()
            return HttpResponseRedirect('/onlinequiz/account/acc-details')

    context["form"] = user_form
    context["formset"] = formset
    return render(request, "onlinequiz/account_edit.html", context)

def accountRedirect(request):
    return redirect('account', current_menu='acc-details')

def account(request, current_menu):
    """
    Handles display for submission & test list, challenge statistics, and account details

    :param request: submitted request
    :param current_menu: the current menu the user is located at
    :type request: HttpRequest
    :type current_menu: str
    :return: Renders the corresponding page
    """
    context = {
        'menu_list': {k: v['name'] for k, v in menu_list.items()},
        'current_menu': current_menu,
    }
    student = request.user.studentuser
    if current_menu == 'submissions':
        context['submissions'] = Submission.objects.filter(student=student).order_by('-submission_time')
    elif current_menu == 'challenge':
        # Get the next hero
        next_hero = Hero.objects.all().filter(price__gt=student.current_hero.price).order_by('price')
        if next_hero:
            context['next_hero'] = next_hero[0]
            context['price_diff'] = context['next_hero'].price - student.current_hero.price
            context['progress'] = student.total_points - student.current_hero.price

        # Get canvas assets
        ownedHero = Hero.objects.filter(price__lte=student.total_points)
        context['canvas_asset'] = GameCanvas.objects.filter(rank_req__in=ownedHero).order_by('rank_req__id')
        context['canvas_asset_json'] = serializers.serialize('json', context['canvas_asset'], fields=('image', 'pos_x', 'pos_y'))
    elif current_menu == 'test':
        context['sets'] = StudentDoTest.objects.filter(student=student)
    elif current_menu == 'acc-details':
        submission = Submission.objects.filter(student=student).exclude(question__tag__isnull=True)
        context['summary'] = list(submission.values('question__tag__tag').annotate(count=Count('id'), avg=Avg('score', output_field=IntegerField())))
    return render(request, menu_list[current_menu]['html'], context)

def submissionDetails(request, id):
    """
    Displays the student's past submission details for one question

    :param request: submitted request
    :param id: submission id
    :type request: HttpRequest
    :type id: int
    :return: Renders the submission_details page
    """
    submission = Submission.objects.get(id=id)
    if submission.question.explanation:
        submission.question.explanation = markdownify(submission.question.explanation)
    context = {
        'menu_list': {k: v['name'] for k, v in menu_list.items()},
        'current_menu': 'test' if hasattr(submission.set, 'testset') else 'submissions',
        'submission': submission,
    }
    if submission.test_case_id:
        test_case = submission.test_case_id.split(' ')
        context['test_cases'] = test_case

    return render(request, 'onlinequiz/submission_details.html', context)

def testDetails(request, id):
    """
    Displays the breakdown of a question list for a particular test set

    :param request: submitted request
    :param id: StudentDoTest id
    :type request: HttpRequest
    :type id: int
    :return: Renders the account_test_details page
    """
    sdt = StudentDoTest.objects.get(id=id)
    submissions = sdt.testsubmission_set.all()
    context = {
        'menu_list': {k: v['name'] for k, v in menu_list.items()},
        'current_menu': 'test',
        'submissions': submissions,
        'set': sdt.set,
        'sdt': sdt,
    }
    return render(request, 'onlinequiz/account_test_details.html', context)

FYP/onlinequiz/views/admin_view.py
from django.http import JsonResponse
from onlinequiz.forms import *
from onlinequiz.models import *

def loadQuestion(request):
    tag_id = request.GET.getlist('tag_id[]')
    diff_id = request.GET.getlist('diff_id[]')
    data = {
        "results": [
        ]
    }
    questions = Question.objects.all()
    if diff_id:
        questions = questions.filter(difficulty__in=diff_id)
    if tag_id:
        questions = questions.filter(tag__id__in=tag_id)
        tags = Tag.objects.filter(id__in=tag_id)
    else:
        tags = Tag.objects.all()
    questions = questions.distinct()
    for question in questions:
        data["results"].append(
            {
                "id": question.id,
                "text": question.question,
                "tag": question.tag_comma,
                "diff": question.difficulty,
            })
    return JsonResponse(data)

FYP/onlinequiz/views/user_view.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import JsonResponse
from onlinequiz.forms import *
from onlinequiz.models import *
from django.contrib.auth import login, authenticate


def checkUser(request):
    """
    Checks if it is the first time for students logging in. If yes, allow students to set their password

    :param request: submitted request
    :type request: HttpRequest
    :return: returns user status
    :rtype: JsonResponse
    """
    if request.method == 'POST':
        username = request.POST.get('username')
        user = User.objects.filter(username=username)
        context = {
            'success': False
        }
        if user.exists():
            if not(user[0].has_usable_password()):
                context['success'] = True
                login(request, user[0])
        return JsonResponse(status=200, data=context)

# Not used, user is created through import/export
def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            s = StudentUser(user=user, matric=form.cleaned_data.get('matric'), group=form.cleaned_data.get('group'),
                            total_points=0, char_gender=form.cleaned_data.get('char_gender'),
                            current_hero=Hero.objects.all().order_by('price')[0])
            s.save()
            login(request, user)
            return redirect('index')
    else:
        form = SignUpForm()
    return render(request, 'registration/signup.html', {'form': form})

FYP/onlinequiz/templates/codeEditor.html
{% extends 'editor.html' %}
{% load index %}
{% load static %}

{% block editor_content %}
<form method="post" id="submission-form">
    {% csrf_token %}
    <!--{{ form }}-->
    {{ form.points }}
    {{ form.submission_type }}
    {{ form.non_field_errors }}
    <div class="container-fluid">
        {{ form.submission.errors }}
        <label for="id_submission">Submission:</label>
        {{ form.submission }}
    </div>
    <button type="submit" class="btn btn-default submit-button" onsubmit="return false" id="check_code" name="check" style="margin-top:10px">Check</button>
    {% if mode == 'Test' %}
    <button type="submit" class="btn btn-default submit-button" onsubmit="return false" id="submit_code" onclick="return confirm('Are you sure you want to submit this? You can only submit once');" name="submit" style="margin-top:10px">Submit</button>
    {% else %}
    <button type="submit" class="btn btn-default submit-button" onsubmit="return false" id="submit_code" name="submit" style="margin-top:10px">Submit</button>
    {% endif %}
</form>
<img id="loadingImg" src="{% static 'images/loading.gif' %}" width="100" height="100">
{% endblock %}

{% block additional_scripts%}
<script>
    var textArea = document.getElementById('id_submission');
    textArea.value = "print('Hello world!')";
    var editor = CodeMirror.fromTextArea(textArea, {
        mode: {name: "python",
               version: 3,
               singleLineStringErrors: false},
        lineNumbers: true,
        autoCloseBrackets: true,
        indentUnit: 4,
        onChange: function(){editor.save()},
    });
    var value = "{{ defaultText|escapejs }}";
    editor.getDoc().setValue(value);
</script>
<script>
    // Refactor later, duplicate code
    $(document).ready(function(){
        var form = $("#submission-form");

        $('.submit-button').click(function() {
              $('#id_submission_type').val($(this).attr('Name'));
        });

        form.submit(function(e){
            e.preventDefault();
            $('.submit-button').prop('disabled', true);
            $.ajax({
                type: form.attr('method'),
                url: '/onlinequiz/{{mode}}/{{set.id}}/{{question.id}}/submit_code/',
                data: form.serialize(),
                success: function (result) {
                    var test_cases = JSON.parse(result.test_cases)
                    var tab_html = "";
                    var content_html = "";
                    var summary_content = "<h3><strong>Style Suggestions:</strong></h3>" +
                        "<figure><pre><code>" + result.suggestion + "</code></pre></figure>";
                    var result_container_html = '<h2>Result</h2>\
                    <div class="row" id="result-box"> \
                    </div> \
                    <div class="row"> \
                        <div id="result-summary"> \
                        </div> \
                    </div>';
                    $("#result-container").html(result_container_html);
                    if (result.sub_type == "check") {
                        var init_box_html = '<ul class="nav nav-tabs" id="result-tabs"> \
                        </ul> \
                        <div class="tab-content" id="result-content"> \
                        </div>'
                        $("#result-box").html(init_box_html);
                        for (i = 0; i < test_cases.length; i++) {
                            var test_case_html = "";
                            test_case_html += "<h4>Input Value</h4>" +
                                "<p>" + test_cases[i].fields.input_value + "</p>";
                            if (result.test_cases_output[i]){
                                test_case_html += "<h4>Expected Output</h4>" +
                                "<figure><pre><code>" + result.test_cases_output[i] + "</code></pre></figure>";
                            }
                                test_case_html += "<h4>Your Output</h4>" +
                                "<figure><pre><code>" + result.output[i] + "</code></pre></figure>";
                            test_case_html += "<h4>Correct</h4>";
                            test_case_html += "<p>" + result.success[i] + "</p><br>";
                            tab_html += '<li class="tabs"><a data-toggle="tab" href="#test_case' + (i + 1) + '">Test Case ' + (i + 1) + '</a></li>'
                            content_html += ('<div id="test_case' + (i + 1) + '" class="diff-content tab-pane fade"> \
                                            <div class="panel panel-default"> \
                                              <div class="panel-body" style="max-height: 35em;overflow-y: scroll" id="result-panel' + (i + 1) + '">' +
                                test_case_html +
                                '</div> \
                                            </div> \
                                        </div>')
                        }
                        $("#result-tabs").html(tab_html);
                        $("#result-content").html(content_html);
                        $(".tabs:first").addClass("active");
                        $(".diff-content:first").addClass("in active");
                    }
                    else if (result.sub_type == "submit") {
                        {% if mode == 'Test' %}
                        alert("Your answer has been submitted");
                        window.location.href = "..";
                        {% else %}
                        var init_box_html = '<div class="panel panel-default"> \
                              <div class="panel-body" style="max-height: 35em;overflow-y: scroll" id="result-panel"> \
                              <ul id="test-case-list"> \
                              </ul> \
                              </div> \
                            </div>';
                        $("#result-box").html(init_box_html);
                        var test_case_html = "";
                        for (i = 0; i < test_cases.length; i++) {
                            test_case_html += '<li class="group-list"><a href="/onlinequiz/test-cases/' + result.test_cases_id[i] +
                                '" target="_blank">Test Case ' + (i + 1);
                            if (result.success[i]) {
                                test_case_html += ' <i class="fa fa-check" style="color:green;"></i></li>';
                            }
                            else {
                                test_case_html += ' <i class="fa fa-times" style="color:red;"></i></li>';
                            }
                        }
                        $("#test-case-list").html(test_case_html);
                        if(result.score==0) {
                            summary_content += "<h3>Please check your code again!</h3><br />This submission will not be recorded"
                        } else {
                            summary_content += "<h3><strong>Correctness: " + Math.round(result.score) + "</strong></h3>";
                        }

                        {% endif %}
                    }
                    var summary_html = '<div class="panel panel-default"> \
                                  <div class="panel-body" style="max-height: 15em;overflow-y: scroll" id="result-panel">' +
                        summary_content +
                        '</div> \
                                </div>'
                    $("#result-summary").html(summary_html);
                    $('.submit-button').prop('disabled', false);
                },
                error: function (result) {
                    alert("Request failed");
                    $('.submit-button').prop('disabled', false);
                },
            });
        });
    });
</script>
{% endblock %}

FYP/onlinequiz/templates/gameCodeEditor.html
{% extends 'gameEditor.html' %}
{% load index %}
{% load static %}

{% block editor_content %}
<form method="post" id="submission-form">
    {% csrf_token %}
    <!--{{ form }}-->
    {{ form.points }}
    {{ form.submission_type }}
    {{ form.non_field_errors }}
        {{ form.submission.errors }}
        <label for="id_submission">Submission:</label>
        {{ form.submission }}
    <button type="submit" class="btn btn-default submit-button" id="check_code" name="check" style="margin-top:10px">Check</button>
    <button type="submit" class="btn btn-default submit-button" id="submit_code" name="submit" style="margin-top:10px">Submit</button>
</form>
<img id="loadingImg" src="{% static 'images/loading.gif' %}" width="100" height="100">
{% endblock %}

{% block additional_scripts%}
<script>
    var textArea = document.getElementById('id_submission');
    textArea.value = "print('Hello world!')";
    var editor = CodeMirror.fromTextArea(textArea, {
        mode: {name: "python",
               version: 3,
               singleLineStringErrors: false},
        lineNumbers: true,
        autoCloseBrackets: true,
        indentUnit: 4,
        onChange: function(){editor.save()},
    });
    var value = "{{ defaultText|escapejs }}";
    editor.getDoc().setValue(value);
</script>
<script>
    $(document).ready(function(){
        var form = $("#submission-form");

        $('.submit-button').click(function() {
              $('#id_submission_type').val($(this).attr('Name'));
        });

        form.submit(function(e){
            $('.submit-button').prop('disabled', true);
            $.ajax({
                type:form.attr('method'),
                url:'/onlinequiz/{{mode}}/{{set.id}}/{{question.id}}/submit_code/',
                data: form.serialize(),
                success: function(result){
                    if (result.score) {
                     $("#submit_code").trigger( "spriteDialog", [ result.score ]);
                    }
                    var test_cases = JSON.parse(result.test_cases);
                    var tab_html = "";
                    var content_html = "";
                    var summary_content = "<h3><strong>Style Suggestions:</strong></h3>" +
                            "<figure><pre><code>" + result.suggestion + "</code></pre></figure>";
                    var result_container_html = '<h2>Result</h2>\
                    <div class="row" id="result-box"> \
                    </div> \
                    <div class="row"> \
                        <div id="result-summary"> \
                        </div> \
                    </div>';
                    $("#result-container").html(result_container_html);
                    if (result.sub_type == "check") {
                        var init_box_html = '<ul class="nav nav-tabs" id="result-tabs"> \
                        </ul> \
                        <div class="tab-content" id="result-content"> \
                        </div>'
                        $("#result-box").html(init_box_html);
                        for (i = 0; i < test_cases.length; i++) {
                            var test_case_html = "";
                            test_case_html += "<h4>Input Value</h4>" +
                                "<p>" + test_cases[i].fields.input_value + "</p>";
                            if (result.test_cases_output[i]){
                                test_case_html += "<h4>Expected Output</h4>" +
                                "<figure><pre><code>" + result.test_cases_output[i] + "</code></pre></figure>";
                            }
                                test_case_html += "<h4>Your Output</h4>" +
                                "<figure><pre><code>" + result.output[i] + "</code></pre></figure>";
                            test_case_html += "<h4>Correct</h4>";
                            test_case_html += "<p>" + result.success[i] + "</p><br>";
                            tab_html += '<li class="tabs"><a data-toggle="tab" href="#test_case' + (i + 1) + '">Test Case ' + (i + 1) + '</a></li>'
                            content_html += ('<div id="test_case' + (i + 1) + '" class="diff-content tab-pane fade"> \
                                            <div class="panel panel-default"> \
                                              <div class="panel-body" style="max-height: 35em;overflow-y: scroll" id="result-panel' + (i + 1) + '">' +
                                test_case_html +
                                '</div> \
                                            </div> \
                                        </div>')
                        }
                        $("#result-tabs").html(tab_html);
                        $("#result-content").html(content_html);
                        $(".tabs:first").addClass("active");
                        $(".diff-content:first").addClass("in active");
                    }
                    else if (result.sub_type == "submit") {
                        var init_box_html = '<div class="panel panel-default"> \
                              <div class="panel-body" style="max-height: 35em;overflow-y: scroll" id="result-panel"> \
                              <ul id="test-case-list"> \
                              </ul> \
                              </div> \
                            </div>';
                        $("#result-box").html(init_box_html);
                        var test_case_html = "";
                        for (i = 0; i < test_cases.length; i++) {
                            test_case_html += '<li class="group-list"><a href="/onlinequiz/test-cases/' + result.test_cases_id[i] +
                                '" target="_blank">Test Case ' + (i+1);
                            if (result.success[i]) {
                                test_case_html += ' <i class="fa fa-check" style="color:green;"></i></li>';
                            }
                            else {
                                test_case_html += ' <i class="fa fa-times" style="color:red;"></i></li>';
                            }
                        }
                        $("#test-case-list").html(test_case_html);
                        if(result.score==0) {
                            summary_content += "<h3>Please check your code again!</h3><br />This submission will not be recorded"
                        } else {
                            summary_content += "<h3><strong>Correctness: " + Math.round(result.score) + "</strong></h3>";
                        }
                        if (result.points) {
                            summary_content += "<h3><strong>You earned " + Math.round(result.points) + " points</strong></h3>";
                        }
                    }
                    var summary_html = '<div class="panel panel-default"> \
                                  <div class="panel-body" style="max-height: 20em;overflow-y: scroll" id="result-panel">' +
                            summary_content +
                            '</div> \
                                </div>'
                    $("#result-summary").html(summary_html);
                    $('.submit-button').prop('disabled', false);
            },
                error: function (result) {
                    alert("Request failed");
                    $('.submit-button').prop('disabled', false);
                },
            });
            e.preventDefault()
        });
    });
</script>
{% endblock %}

FYP/onlinequiz/templates/gameMcqEditor.html
{% extends 'gameEditor.html' %}
{% load index %}
{% load static %}

{% block editor_content %}
<form method="post" id="submission-form">
    {% csrf_token %}
    <!--{{ form }}-->
    {{ form.points }}
    {{ form.non_field_errors }}
    <div class="container-fluid">
        {{ form.submission.errors }}
        <label for="id_submission">Choices:</label>
        <div id="mcq-choices">
            {{ form.choice }}
        </div>
    </div>
    <button type="submit" class="btn btn-default" id="submit_code" name="submit" style="margin-top:10px">Submit</button>
</form>
<img id="loadingImg" src="{% static 'images/loading.gif' %}" width="100" height="100">
{% endblock %}

{% block additional_scripts%}
<script>
$(document).ready(function(){
    var form = $("#submission-form");
    form.submit(function(e){
        $.ajax({
            type: form.attr('method'),
            url: '/onlinequiz/{{mode}}/{{set.id}}/{{question.id}}/submit_mcq/',
            data: form.serialize(),
            success: function (result) {
                var result_container_html = '<h2>Result</h2>\
                    <div class="row" id="result-box"> \
                    </div> \
                    <div class="row"> \
                        <div id="result-summary"> \
                        </div> \
                    </div>';
                $("#result-container").html(result_container_html);
                if (result["correct"]) {
                    var correct = "Your answer is correct"
                } else {
                    var correct = "Your answer is incorrect"
                }
                var init_box_html = '<div class="panel panel-default"> \
                              <div class="panel-body" id="result-panel"> \
                              <h4>Your choice: <strong>' + result["choice"] + '</strong></h4> \
                              <h4>' + correct + '</h4>\
                              </div> \
                            </div>';
                if (result.points) {
                    init_box_html += "<h3><strong>You earned " + Math.round(result.points) + " points</strong></h3>";
                }
                $("#result-box").html(init_box_html);
            }
        });
        e.preventDefault();
    });
});
</script>
{% endblock %}

FYP/onlinequiz/templates/questions_dropdown.html
{% for tag in tags %}
<optgroup label="{{ tag.tag }}">
    {% for question in questions %}
    {% if tag in question.tag.all %}
    <option value="{{ question.id }}">{{ question.set_display }} |
        {% for tag in question.tag.all %}
            {{ tag }}{% if not forloop.last %}, {% endif %}
        {% endfor %}
    </option>
    {% endif %}
    {% endfor %}
</optgroup>
{% endfor %}